# Fanout exchange za reklamiranje
advertising.exchange=fanout_exchange_ads
# Queue-ovi agencija (mo?e ih biti vi?e, ali ovde samo primer za test)
advertising.queue1=ads_queue_agency1
advertising.queue2=ads_queue_agency2
advertising.queue3=ads_queue_agency3

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
