spring.application.name=isa-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/ISA
spring.datasource.username=postgres
spring.datasource.password=super
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect